### ISSUE TITLE
Intro screens overall

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHResponseToMotionRegardingChangeOfDomicile#5]
I think someone needs to go through and think about how to weave the info from the LHI version into the framework slides. Otherwise we end up with a lot of duplication and too much intro at the beginning. This is a place we have to be a bit more thoughtful/creative and come up with a reasonable way to combine the two. We can also leave framework slides out, when appropriate, but if you recreate LHI _and_ include all the framework slides, it's just too much.

I could take a stab at doing that and make a pull request if that makes sense to you @RamiLorca

**Comment by RamiLorca** [comment]
@ekressmiller That makes sense if we're getting lots of duplicated info. If you want to take a stab it and then do a PR, that sounds good to me. I'd also be totally fine with taking this on myself, especially if we could do a quick overview at the next dev meeting.

**Comment by ekressmiller** [comment]
Thanks Rami, let's discuss/decide at the meeting tomorrow.

**Comment by ekressmiller** [comment]
@RamiLorca I will take a stab at this and do a pull request.
