### ISSUE TITLE
Include document upload feature?

### ISSUE THREAD

**Issue by RamiLorca** [mplp/docassemble-MLHResponseToMotionRegardingChangeOfDomicile#53]
We've been talking about adding the same document upload feature that was added to the MRCD interview, but I'm actually wondering if it makes sense to also add it here. 

In the MRCD interview, the feature comes up when a user indicates they're escaping DV and have documents related to that situation. However, for this interview, I went over the LHI version again and couldn't really find any places where it might make sense to add a document uploader. The only other option I can think of would be some sort of catch-all screen at the end, where the user can have the option of attaching anything relevant to their filing. 

@ekressmiller, what do you think?

**Comment by ekressmiller** [comment]
@RamiLorca Great point Rami, I think you're right. Just went over the LHI version too and came to the same conclusion.

I think you can leave it out of the response tool.
